// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKtyC4OXc8vqA2S9asxRTRuJ9HmTUQU0c',
    appId: '1:132503870031:web:f7047f7fa62ebd3009283a',
    messagingSenderId: '132503870031',
    projectId: 'teamup-eaeef',
    authDomain: 'teamup-eaeef.firebaseapp.com',
    storageBucket: 'teamup-eaeef.firebasestorage.app',
    measurementId: 'G-L411DY9G97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQBfSR8ALfErbnA8MLVp5UR2chYq5E-Uw',
    appId: '1:132503870031:android:b2efbc2d788b3f5309283a',
    messagingSenderId: '132503870031',
    projectId: 'teamup-eaeef',
    storageBucket: 'teamup-eaeef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJzhLosyNMc83U2LOz9S0gwY_5FjY-i4',
    appId: '1:132503870031:ios:34b96f863c6654a909283a',
    messagingSenderId: '132503870031',
    projectId: 'teamup-eaeef',
    storageBucket: 'teamup-eaeef.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcJzhLosyNMc83U2LOz9S0gwY_5FjY-i4',
    appId: '1:132503870031:ios:34b96f863c6654a909283a',
    messagingSenderId: '132503870031',
    projectId: 'teamup-eaeef',
    storageBucket: 'teamup-eaeef.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKtyC4OXc8vqA2S9asxRTRuJ9HmTUQU0c',
    appId: '1:132503870031:web:f4ca19994fc0bccb09283a',
    messagingSenderId: '132503870031',
    projectId: 'teamup-eaeef',
    authDomain: 'teamup-eaeef.firebaseapp.com',
    storageBucket: 'teamup-eaeef.firebasestorage.app',
    measurementId: 'G-98SBY9GJE3',
  );
}
